### ISSUE TITLE
Demo no longer works

### ISSUE THREAD

**Issue by lanrat** [orangejulius/webpassmap#1]
https://webpassmap.juliansimioni.com/ seems to be down.

**Comment by orangejulius** [comment]
Thanks! :) I just enabled HSTS on juliansimioni.com, but don't have a cert for webpassmap.juliansimioni.com. It's on my todo list to fix

**Comment by orangejulius** [comment]
The url is now https://juliansimioni.com/webpassmap/. Unfortunately I don't plan on buying a certificate for the webpassmap subdomain, so I can't do a redirect, but the Readme URL is now updated.
